name: 'md5-check'
description: 'check your update's file, auto fix if error.'
branding:
  icon: 'anchor'  
  color: 'gray-dark'

inputs:
  dir-path:
    description: 'where is your update file?'
    required: true
  commit-message:
    default: 'md5 fix'
    required: true
  committer-email:
    default: 'taromati2@foxmail.com'
    required: true
  committer-name:
    default: 'Taromati2'
    required: true
runs:
  using: "composite"
  steps:
    - id: check
      run: ${{ github.action_path }}\md5-checker.exe ${{ inputs.dir-path }}
      shell: cmd
    - id: commit
      uses: actions-go/push@master
      with:
        author-email: ${{ inputs.committer-email }}
        author-name: ${{ inputs.committer-name }}
        commit-message: ${{ inputs.commit-message }}
        remote: origin
