name: 'md5file-CI-build'
description: 'auto build your update file.'
branding:
  icon: 'anchor'
  color: 'gray-dark'

inputs:
  dir-path:
    default: '.'
    description: 'where is your update file?'
    required: true
  build-mode:
    default: 'ghost_dir'
    description: 'ghost_dir(for ghost & each shell) or other(only for a dir)'
    required: true
  commit-message:
    default: 'md5 fix~'
    required: false
  committer-email:
    default: 'taromati2@foxmail.com'
    required: false
  committer-name:
    default: 'Taromati2'
    required: false
  no-push:
    description: 'no push will be performed if this value is true'
    default: false
    required: false
  token:
    description: >
      Auth token used to fetch the repository. The token is stored in the local
      git config, which enables your scripts to run authenticated git commands.
      The post-job step removes the token from the git config. [Learn more about
      creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
    required: false
runs:
  using: "composite"
  steps:
    - id: build
      run: |
        ${{ github.action_path }}\md5-CI-builder.exe ${{ inputs.build-mode }} ${{ inputs.dir-path }}
        git add -A
      shell: cmd
    - if: ${{ inputs.no-push == 'false' && startsWith(github.ref, 'refs/tags/') }}
      run: echo "::warning title=ref is a tag::The ref should not be a tag, consider using tags-ignore to avoid the tag being used as a ref to trigger this workflow"
      shell: cmd
    - id: commit
      if: ${{ inputs.no-push == 'false' && !startsWith(github.ref, 'refs/tags/') }}
      uses: actions-go/push@master
      with:
        author-email: ${{ inputs.committer-email }}
        author-name: ${{ inputs.committer-name }}
        commit-message: ${{ inputs.commit-message }}
        remote: origin
        token: ${{ inputs.token }}

